// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/anomaly-groups": {
            "get": {
                "tags": [
                    "anomaly-groups"
                ],
                "summary": "Get anomaly groups",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.AnomalyGroup"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/anomaly-groups/{id}": {
            "get": {
                "tags": [
                    "anomaly-groups"
                ],
                "summary": "Get anomaly group by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anomaly Group ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AnomalyGroupWithAnomalies"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Anomaly": {
            "type": "object",
            "properties": {
                "anomalyGroupId": {
                    "type": "integer",
                    "example": 1
                },
                "createdAt": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "dataSource": {
                    "type": "string",
                    "example": "SYNTHETIC"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "metadata": {
                    "type": "object"
                }
            }
        },
        "models.AnomalyGroup": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "lastActivityAt": {
                    "type": "string",
                    "example": "2024-01-15T14:30:00Z"
                },
                "latitude": {
                    "type": "number",
                    "example": 59.9139
                },
                "longitude": {
                    "type": "number",
                    "example": 10.7522
                },
                "mmsi": {
                    "type": "integer",
                    "example": 123456789
                },
                "startedAt": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "type": {
                    "type": "string",
                    "example": "speed_anomaly"
                }
            }
        },
        "models.AnomalyGroupWithAnomalies": {
            "type": "object",
            "properties": {
                "anomalies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Anomaly"
                    }
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "lastActivityAt": {
                    "type": "string",
                    "example": "2024-01-15T14:30:00Z"
                },
                "latitude": {
                    "type": "number",
                    "example": 59.9139
                },
                "longitude": {
                    "type": "number",
                    "example": 10.7522
                },
                "mmsi": {
                    "type": "integer",
                    "example": 123456789
                },
                "startedAt": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "type": {
                    "type": "string",
                    "example": "speed_anomaly"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid_request"
                },
                "message": {
                    "type": "string",
                    "example": "The request parameters are invalid"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "AIS Anomaly Detection API",
	Description:      "API for querying AIS anomaly detection data",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
